services:
  mysql:
    image: mysql:8.4
    container_name: mysql-chat-container
    ports:
      - "33067:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234